/**
 * ${product_name} SDK — Deno License Management Client
 * Generated by Websmith License API Center
 * Runtime: deno | Version: ${kit_version}
 */

// ---- Config ----
interface ApiConfig {
  api: {
    url: string;
    version: string;
    public_key: string;
    secret: string;
    timeout: number;
    retry_count: number;
  };
  product: {
    id: string;
    name: string;
  };
  offline: {
    cache_days: number;
  };
  trial: {
    enabled: boolean;
  };
  branding: Record<string, string>;
}

function loadConfig(path?: string): ApiConfig {
  const paths = path
    ? [path]
    : ['./config/api-config.json', '../config/api-config.json'];
  for (const p of paths) {
    try {
      const raw = Deno.readTextFileSync(p);
      return JSON.parse(raw) as ApiConfig;
    } catch {
      continue;
    }
  }
  throw new Error(
    'api-config.json not found. Checked: ' + paths.join(', ')
  );
}

// ---- Crypto ----
function toHex(buf: ArrayBuffer): string {
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

async function hmacSha256(
  secret: string,
  message: string
): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message));
  return btoa(String.fromCharCode(...new Uint8Array(sig)));
}

function generateTimestamp(): string {
  return new Date().toISOString().replace(/.d{3}Z$/, 'Z');
}

function generateNonce(): string {
  const arr = new Uint8Array(16);
  crypto.getRandomValues(arr);
  return toHex(arr.buffer);
}

async function signRequest(
  payload: Record<string, unknown>,
  secret: string,
  timestamp: string,
  nonce: string,
  method = 'POST',
  path = '',
  query = ''
): Promise<string> {
  const json = JSON.stringify(payload, Object.keys(payload).sort());
  const bhash = toHex(
    await crypto.subtle.digest('SHA-256', new TextEncoder().encode(json))
  );
  const message = method + '\n' + path + '\n' + query + '\n' + bhash + '\n' + timestamp + '\n' + nonce;
  return await hmacSha256(secret, message);
}

// ---- API Error ----
class ApiError extends Error {
  statusCode: number;
  data: Record<string, unknown>;

  constructor(statusCode: number, message: string, data: Record<string, unknown> = {}) {
    super(message);
    this.name = 'ApiError';
    this.statusCode = statusCode;
    this.data = data;
  }
}

// ---- Hardware Fingerprint ----
class HardwareFingerprint {
  private _fingerprint: string | null = null;
  private _identifiers: Record<string, string> | null = null;

  async generate(): Promise<{ fingerprint: string; macAddresses: string[]; os: string }> {
    if (this._fingerprint) {
      return { fingerprint: this._fingerprint, macAddresses: [], os: Deno.build.os };
    }
    const identifiers = await this._collectIdentifiers();
    const combined = Object.values(identifiers).join('|');
    const hash = toHex(
      await crypto.subtle.digest('SHA-256', new TextEncoder().encode(combined))
    );
    this._fingerprint = hash;
    this._identifiers = identifiers;
    const macs = identifiers.mac ? identifiers.mac.split(',') : [];
    return { fingerprint: hash, macAddresses: macs, os: Deno.build.os };
  }

  async getFingerprint(): Promise<string> {
    const result = await this.generate();
    return result.fingerprint;
  }

  private async _collectIdentifiers(): Promise<Record<string, string>> {
    const ids: Record<string, string> = {};
    // CPU / OS info
    ids.os = Deno.build.os + '-' + Deno.osRelease();
    // MAC addresses
    const macs: string[] = [];
    try {
      const ifaces = Deno.networkInterfaces();
      for (const iface of ifaces) {
        if (!iface.internal && iface.mac !== '00:00:00:00:00:00') {
          macs.push(iface.mac);
        }
      }
    } catch {
      // network interfaces unavailable
    }
    if (macs.length > 0) {
      ids.mac = macs.slice(0, 3).join(',');
    }
    // Hostname
    try {
      ids.hostname = Deno.hostname();
    } catch {
      // hostname unavailable
    }
    return ids;
  }

  getIdentifiers(): Record<string, string> {
    return this._identifiers || {};
  }
}

// ---- Cache Manager ----
class CacheManager {
  private _config: ApiConfig;
  private _cacheDir: string;
  private _cacheFile: string;
  private _tmpFile: string;
  private _corruptFile: string;
  private _ttlDays: number;
  private _cache: Record<string, { value: unknown; cached_at: number }> | null = null;

  constructor(config: ApiConfig) {
    this._config = config;
    const safeName = config.product.id.replace(/[^a-zA-Z0-9_-]/g, '_');
    const home = Deno.env.get('HOME') || Deno.env.get('USERPROFILE') || '.';
    this._cacheDir = home + '/.websmith/' + safeName;
    this._cacheFile = this._cacheDir + '/cache.json';
    this._tmpFile = this._cacheDir + '/cache.tmp';
    this._corruptFile = this._cacheDir + '/cache.corrupt';
    this._ttlDays = config.offline?.cache_days ?? 0;
  }

  private _ensureDir(): void {
    try {
      Deno.mkdirSync(this._cacheDir, { recursive: true });
    } catch {
      // directory may already exist
    }
  }

  private _loadCache(): Record<string, { value: unknown; cached_at: number }> {
    if (this._cache) return this._cache;
    this._ensureDir();
    try {
      const raw = Deno.readTextFileSync(this._cacheFile);
      this._cache = JSON.parse(raw);
    } catch {
      try {
        Deno.renameSync(this._cacheFile, this._corruptFile);
      } catch {
        // no corrupt file to preserve
      }
      this._cache = {};
    }
    return this._cache;
  }

  private _saveCache(): void {
    if (!this._cache) return;
    this._ensureDir();
    try {
      Deno.writeTextFileSync(this._tmpFile, JSON.stringify(this._cache));
      Deno.renameSync(this._tmpFile, this._cacheFile);
    } catch {
      try { Deno.removeSync(this._tmpFile); } catch {/* ok */}
    }
  }

  private _isExpired(entry: { value: unknown; cached_at: number }): boolean {
    const ttlSeconds = this._ttlDays * 86400;
    return (Date.now() / 1000 - entry.cached_at) > ttlSeconds;
  }

  get<T = unknown>(key: string): T | null {
    const cache = this._loadCache();
    const entry = cache[key];
    if (!entry) return null;
    if (this._isExpired(entry)) {
      this.delete(key);
      return null;
    }
    return entry.value as T;
  }

  set(key: string, value: unknown): void {
    const cache = this._loadCache();
    cache[key] = { value, cached_at: Date.now() / 1000 };
    this._saveCache();
  }

  delete(key: string): void {
    const cache = this._loadCache();
    if (key in cache) {
      delete cache[key];
      this._saveCache();
    }
  }

  clear(): void {
    this._cache = {};
    this._saveCache();
  }

  isCacheValid(): boolean {
    const cache = this._loadCache();
    const entry = cache['license_status'];
    if (!entry) return false;
    return !this._isExpired(entry);
  }

  getLicenseStatus<T = unknown>(): T | null {
    return this.get<T>('license_status');
  }

  setLicenseStatus(status: Record<string, unknown>): void {
    this.set('license_status', status);
  }

  invalidateLicenseStatus(): void {
    this.delete('license_status');
  }

}

// ---- API Client ----
class Client {
  private _config: ApiConfig;
  private _baseUrl: string;
  private _apiVersion: string;
  private _apiKey: string;
  private _apiSecret: string;
  private _timeout: number;
  private _retryCount: number;
  private _productId: string;
  private _hardware: HardwareFingerprint;
  private _cache: CacheManager | null;

  constructor(
    config: ApiConfig,
    hardware?: HardwareFingerprint,
    cache?: CacheManager
  ) {
    this._config = config;
    this._baseUrl = (config.api?.url || '').replace(/\/+$/, '');
    this._apiVersion = config.api?.version || 'v1';
    this._apiKey = config.api?.public_key || '';
    this._apiSecret = config.api?.secret || '';
    this._timeout = (config.api?.timeout || 30000) / 1000;
    this._retryCount = config.api?.retry_count ?? 3;
    this._productId = config.product?.id || '';
    this._hardware = hardware || new HardwareFingerprint();
    this._cache = cache || null;
  }

  private async _signHeaders(
    payload: Record<string, unknown>,
    method = 'POST',
    path = '',
    query = ''
  ): Promise<Record<string, string>> {
    const timestamp = generateTimestamp();
    const nonce = generateNonce();
    const signature = await signRequest(
      payload, this._apiSecret, timestamp, nonce, method, path, query
    );
    return {
      'x-api-key': this._apiKey,
      'x-timestamp': timestamp,
      'x-nonce': nonce,
      'x-signature': signature,
      'content-type': 'application/json',
    };
  }

  async request(
    endpoint: string,
    payload: Record<string, unknown>,
    retries?: number
  ): Promise<Record<string, unknown>> {
    const url = this._baseUrl + '/api/' + this._apiVersion + '/' + endpoint;
    const maxRetries = retries ?? this._retryCount;
    const requestPayload: Record<string, unknown> = { ...payload };
    if (this._productId) {
      requestPayload['product_id'] = this._productId;
    }
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      const apiPath = '/api/' + this._apiVersion + '/' + endpoint;
      const headers = await this._signHeaders(requestPayload, 'POST', apiPath, '');
      try {
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), this._timeout * 1000);
        const response = await fetch(url, {
          method: 'POST',
          headers,
          body: JSON.stringify(requestPayload),
          signal: controller.signal,
        });
        clearTimeout(timer);
        let data: Record<string, unknown> = {};
        try {
          data = await response.json();
        } catch {
          const text = await response.text();
          if (text) data = { message: text };
        }
        if (response.ok) return data;

        if (response.status === 429) {
          if (attempt < maxRetries) {
            const retryAfter = parseInt(response.headers.get('retry-after') || '5', 10);
            await this._sleep(retryAfter * 1000);
            continue;
          }
          throw new ApiError(429, 'Rate limit exceeded', data);
        }
        if (response.status >= 500) {
          if (attempt < maxRetries) {
            await this._sleep((attempt + 1) * 2000);
            continue;
          }
          throw new ApiError(response.status, 'Server error', data);
        }
        const message =
          (data.message as string) ||
          (data.error as string) ||
          'HTTP ' + response.status;
        throw new ApiError(response.status, message, data);
      } catch (err) {
        if (err instanceof ApiError) throw err;
        if (err instanceof DOMException && err.name === 'AbortError') {
          if (attempt < maxRetries) {
            await this._sleep((attempt + 1) * 2000);
            continue;
          }
          throw new ApiError(504, 'Request timeout after ' + this._timeout + 's');
        }
        if (err instanceof TypeError && err.message.includes('fetch')) {
          if (attempt < maxRetries) {
            await this._sleep((attempt + 1) * 2000);
            continue;
          }
          throw new ApiError(503, 'Connection error: ' + err.message);
        }
        if (attempt < maxRetries) {
          await this._sleep((attempt + 1) * 2000);
          continue;
        }
        throw new ApiError(500, 'Request failed: ' + (err as Error).message);
      }
    }
    throw new ApiError(500, 'Failed after ' + maxRetries + ' retries');
  }

  private _sleep(ms: number): Promise<void> {
    return new Promise((r) => setTimeout(r, ms));
  }

  // ---- Public API methods ----

  async validateLicense(licenseKey: string, hardwareId?: string): Promise<Record<string, unknown>> {
    if (!hardwareId) hardwareId = await this._hardware.getFingerprint();
    const payload: Record<string, unknown> = { action: 'validate', license_key: licenseKey, hardware_id: hardwareId };
    if (this._cache && this._cache.isCacheValid()) {
      const cached = this._cache.getLicenseStatus<Record<string, unknown>>();
      if (cached) return cached;
    }
    const response = await this.request('license', payload);
    if (this._cache && response.valid) {
      this._cache.setLicenseStatus(response);
    }
    return response;
  }

  async activateLicense(
    licenseKey: string,
    hardwareId?: string,
    deviceName?: string
  ): Promise<Record<string, unknown>> {
    if (!hardwareId) hardwareId = await this._hardware.getFingerprint();
    const payload: Record<string, unknown> = {
      action: 'activate',
      license_key: licenseKey,
      hardware_id: hardwareId,
    };
    if (deviceName) payload.device_name = deviceName;
    const response = await this.request('license', payload);
    if (this._cache) this._cache.invalidateLicenseStatus();
    return response;
  }

  async deactivateLicense(
    licenseKey: string,
    hardwareId?: string
  ): Promise<Record<string, unknown>> {
    if (!hardwareId) hardwareId = await this._hardware.getFingerprint();
    const payload: Record<string, unknown> = {
      action: 'deactivate',
      license_key: licenseKey,
      hardware_id: hardwareId,
    };
    const response = await this.request('license', payload);
    if (this._cache) this._cache.invalidateLicenseStatus();
    return response;
  }

  async renewLicense(
    licenseKey: string,
    extraDays?: number
  ): Promise<Record<string, unknown>> {
    const payload: Record<string, unknown> = { action: 'renew', license_key: licenseKey };
    if (extraDays !== undefined) payload.extra_days = extraDays;
    const response = await this.request('license', payload);
    if (this._cache) this._cache.invalidateLicenseStatus();
    return response;
  }

  async startTrial(
    email: string,
    customerName = '',
    customerData?: Record<string, unknown>
  ): Promise<Record<string, unknown>> {
    const hardwareId = await this._hardware.getFingerprint();
    const payload: Record<string, unknown> = {
      action: 'start',
      customer_email: email,
      customer_name: customerName,
      hardware_id: hardwareId,
    };
    if (customerData) payload.customer_data = customerData;
    return await this.request('trial', payload);
  }

  async checkTrial(hardwareId?: string): Promise<Record<string, unknown>> {
    if (!hardwareId) hardwareId = await this._hardware.getFingerprint();
    return await this.request('trial', {
      action: 'status',
      hardware_id: hardwareId,
    });
  }

  async convertTrial(
    hardwareId?: string,
    plan?: string,
    customerName?: string,
    customerEmail?: string
  ): Promise<Record<string, unknown>> {
    if (!hardwareId) hardwareId = await this._hardware.getFingerprint();
    const payload: Record<string, unknown> = {
      action: 'convert',
      hardware_id: hardwareId,
    };
    if (plan) payload.plan = plan;
    if (customerName) payload.customer_name = customerName;
    if (customerEmail) payload.customer_email = customerEmail;
    const response = await this.request('trial', payload);
    if (this._cache) this._cache.invalidateLicenseStatus();
    return response;
  }

  async bindDevice(
    licenseKey: string,
    hardwareId?: string,
    deviceName?: string
  ): Promise<Record<string, unknown>> {
    if (!hardwareId) hardwareId = await this._hardware.getFingerprint();
    const payload: Record<string, unknown> = {
      action: 'bind',
      license_key: licenseKey,
      hardware_id: hardwareId,
    };
    if (deviceName) payload.device_name = deviceName;
    return await this.request('device', payload);
  }

  async getTrialStatus(hardwareId?: string): Promise<Record<string, unknown>> {
    if (!hardwareId) hardwareId = await this._hardware.getFingerprint();
    return await this.request('trial', { action: 'status', hardware_id: hardwareId });
  }

  async getProducts(): Promise<Record<string, unknown>> {
    return await this.request('store/products', { action: 'list' });
  }
}

// ---- License Status ----
class LicenseStatus {
  valid: boolean;
  status: string;
  expiresAt: string | null;
  daysRemaining: number;
  plan: string | null;
  hardwareId: string | null;
  message: string | null;

  constructor(data: {
    valid: boolean;
    status: string;
    expires_at?: string | null;
    days_remaining?: number;
    plan?: string | null;
    hardware_id?: string | null;
    message?: string | null;
  }) {
    this.valid = data.valid;
    this.status = data.status;
    this.expiresAt = data.expires_at || null;
    this.daysRemaining = data.days_remaining || 0;
    this.plan = data.plan || null;
    this.hardwareId = data.hardware_id || null;
    this.message = data.message || null;
  }

  toJSON(): Record<string, unknown> {
    return {
      valid: this.valid,
      status: this.status,
      expires_at: this.expiresAt,
      days_remaining: this.daysRemaining,
      plan: this.plan,
      hardware_id: this.hardwareId,
      message: this.message,
    };
  }

  static fromJSON(data: Record<string, unknown>): LicenseStatus {
    return new LicenseStatus({
      valid: data.valid as boolean,
      status: data.status as string || 'unlicensed',
      expires_at: data.expires_at as string | null,
      days_remaining: data.days_remaining as number || 0,
      plan: data.plan as string | null,
      hardware_id: data.hardware_id as string | null,
      message: data.message as string | null,
    });
  }
}

// ---- License Engine ----
class LicenseEngine {
  private _config: ApiConfig;
  private _hardware: HardwareFingerprint;
  private _cache: CacheManager;
  private _client: Client;
  private _status: LicenseStatus | null = null;
  private _licenseKey: string | null = null;

  constructor(configPath?: string) {
    this._config = loadConfig(configPath);
    this._hardware = new HardwareFingerprint();
    this._cache = new CacheManager(this._config);
    this._client = new Client(this._config, this._hardware, this._cache);
  }

  async initialize(): Promise<LicenseStatus> {
    if (this._cache.isCacheValid()) {
      const cached = this._cache.getLicenseStatus<Record<string, unknown>>();
      if (cached) {
        this._status = LicenseStatus.fromJSON(cached);
        return this._status;
      }
    }
    try {
      const hardwareId = await this._hardware.getFingerprint();
      const response = await this._client.validateLicense(hardwareId);
      this._status = new LicenseStatus({
        valid: response.valid as boolean || false,
        status: response.status as string || 'unlicensed',
        expires_at: response.expires_at as string | null,
        days_remaining: (response.days_left ?? response.days_remaining ?? 0) as number,
        plan: response.plan as string | null,
        hardware_id: hardwareId,
        message: response.message as string | null,
      });
      if (this._status.valid) {
        this._cache.setLicenseStatus(this._status.toJSON());
      }
      return this._status;
    } catch {
      const cached = this._cache.getLicenseStatus<Record<string, unknown>>();
      if (cached) {
        this._status = LicenseStatus.fromJSON(cached);
        return this._status;
      }
      throw new Error('Unable to validate license and no cached status available');
    }
  }

  async validate(licenseKey: string): Promise<Record<string, unknown>> {
    const fp = await this._hardware.getFingerprint();
    const result = await this._client.validateLicense(licenseKey, fp);
    this._status = new LicenseStatus({
      valid: result.valid as boolean || false,
      status: result.status as string || 'unlicensed',
      expires_at: result.expires_at as string | null,
      days_remaining: (result.days_left ?? result.days_remaining ?? 0) as number,
      plan: result.plan as string | null,
      hardware_id: fp,
      message: result.message as string | null,
    });
    return result;
  }

  async activate(licenseKey: string, deviceName?: string): Promise<Record<string, unknown>> {
    const result = await this._client.activateLicense(licenseKey, undefined, deviceName);
    if (result.success) {
      this._licenseKey = licenseKey;
      await this.initialize();
    }
    return result;
  }

  async deactivate(licenseKey?: string): Promise<Record<string, unknown>> {
    const key = licenseKey || this._licenseKey;
    if (!key) throw new Error('License key unavailable. Please provide a key.');
    const result = await this._client.deactivateLicense(key);
    if (result.success) {
      this._cache.invalidateLicenseStatus();
      this._status = null;
      if (!licenseKey) this._licenseKey = null;
    }
    return result;
  }

  async renew(extraDays?: number): Promise<Record<string, unknown>> {
    if (!this._licenseKey) {
      throw new Error('License key unavailable. Please activate first.');
    }
    const result = await this._client.renewLicense(this._licenseKey, extraDays);
    if (result.success) {
      await this.initialize();
    }
    return result;
  }

  async startTrial(
    email: string,
    customerName = '',
    customerData?: Record<string, unknown>
  ): Promise<Record<string, unknown>> {
    const result = await this._client.startTrial(email, customerName, customerData);
    if (result.success) {
      await this.initialize();
    }
    return result;
  }

  async checkTrial(): Promise<Record<string, unknown>> {
    const fp = await this._hardware.getFingerprint();
    return await this._client.checkTrial(fp);
  }

  async convertTrial(plan?: string, customerName?: string, customerEmail?: string): Promise<Record<string, unknown>> {
    const status = await this.initialize();
    if (!status || status.status !== 'trial') {
      throw new Error('No active trial to convert.');
    }
    const hardwareId = await this._hardware.getFingerprint();
    const result = await this._client.convertTrial(hardwareId, plan, customerName, customerEmail);
    if (result.success) {
      if (result.license_key) this._licenseKey = result.license_key as string;
      await this.initialize();
    }
    return result;
  }


  async bindDevice(licenseKey?: string, deviceName?: string): Promise<Record<string, unknown>> {
    const key = licenseKey || this._licenseKey;
    if (!key) throw new Error('License key unavailable.');
    const fp = await this._hardware.getFingerprint();
    const result = await this._client.bindDevice(key, fp, deviceName);
    if (result.success) {
      await this.initialize();
    }
    return result;
  }

  async viewHardwareStatus(): Promise<Record<string, unknown>> {
    const currentHwId = this._hardware.getHardwareId();
    const status = await this.validate();
    const registeredHwId = (status?.data as Record<string, unknown>)?.hardware_id as string || '';
    return { matched: currentHwId === registeredHwId, current_hardware_id: currentHwId, registered_hardware_id: registeredHwId };
  }

  hasLicenseKey(): boolean {
    return this._licenseKey !== null;
  }

  isValid(): boolean {
    if (!this._status) return false;
    if (this._status.status !== 'active') return false;
    if (this._status.expiresAt) {
      return new Date(this._status.expiresAt) > new Date();
    }
    return true;
  }

  getLicenseInfo(): Record<string, unknown> {
    return {
      licenseKey: this._licenseKey,
      status: this._status?.toJSON() || null,
    };
  }
}

export { Client, ApiError, LicenseEngine, LicenseStatus, HardwareFingerprint, CacheManager };
