// Neon media persistence — the single authoritative media store.
// The media system was migrated from MongoDB to Neon: this module owns the
// media_assets table (created/ensured in lib/backend-db getDb) and every
// read/write path used by the public media API routes.
//
// SCHEMA-AGNOSTIC IDS: production media_assets.id is a native SERIAL integer
// (HTTP evidence: registry returns url "/api/media/3"). Code never forces a
// UUID into id — inserts omit the id column and the conflict path uses
// id = DEFAULT, so fresh ids come from the column's own default on both
// serial and uuid-default columns.

import { readFileSync, existsSync } from "fs";
import { join } from "path";
import type { Pool, PoolClient } from "pg";

export type MediaDb = { query: Pool["query"] };

export type MediaAssetRow = {
  id: string | number;
  slot_key: string;
  file_name: string;
  content_type: string;
  file_size: number;
  data?: Buffer;
  updated_at: Date;
};

export type MediaRecord = {
  url: string;
  fileName: string;
  contentType: string;
  fileSize: number;
  updatedAt: string;
};

export function toMediaRecord(row: MediaAssetRow): MediaRecord {
  return {
    url: `/api/media/${row.id}`,
    fileName: row.file_name,
    contentType: row.content_type,
    fileSize: Number(row.file_size),
    updatedAt: row.updated_at instanceof Date ? row.updated_at.toISOString() : String(row.updated_at),
  };
}

export async function getMediaAssets(db: MediaDb): Promise<Record<string, MediaRecord>> {
  const result = await db.query<MediaAssetRow>(
    `SELECT id, slot_key, file_name, content_type, file_size, updated_at
     FROM media_assets
     ORDER BY slot_key`
  );
  const map: Record<string, MediaRecord> = {};
  for (const row of result.rows) {
    map[row.slot_key] = toMediaRecord(row);
  }
  return map;
}

export async function getMediaAssetById(db: MediaDb, id: string): Promise<MediaAssetRow | null> {
  const result = await db.query<MediaAssetRow>(
    `SELECT id, slot_key, file_name, content_type, file_size, data, updated_at
     FROM media_assets
     WHERE id = $1`,
    [id]
  );
  return result.rows[0] ?? null;
}

// Upsert a slot's media with a FRESH id on every upload, so the media URL
// always changes and no browser/CDN can keep serving stale bytes for a
// previously-immutable URL. The id is generated by the column's own default
// (serial nextval, or gen_random_uuid for uuid-default columns) — never forced
// to a literal UUID, which would type-error against an integer column.
export async function upsertMediaAsset(
  db: MediaDb,
  slotKey: string,
  file: { fileName: string; contentType: string; fileSize: number; data: Buffer }
): Promise<MediaRecord> {
  const result = await db.query<MediaAssetRow>(
    `INSERT INTO media_assets (slot_key, file_name, content_type, file_size, data, updated_at)
     VALUES ($1, $2, $3, $4, $5, now())
     ON CONFLICT (slot_key) DO UPDATE SET
       id = DEFAULT,
       file_name = EXCLUDED.file_name,
       content_type = EXCLUDED.content_type,
       file_size = EXCLUDED.file_size,
       data = EXCLUDED.data,
       updated_at = now()
     RETURNING id, slot_key, file_name, content_type, file_size, updated_at`,
    [slotKey, file.fileName, file.contentType, file.fileSize, file.data]
  );
  return toMediaRecord(result.rows[0]);
}

// Non-destructive seed/repair of the production media records. On a FRESH
// database it inserts the two committed seed assets (global_collaboration_video
// from public/videos/API-Center.mp4 + global_collaboration_image from
// public/images/photo-1552664730-d307ca884978.jpg) with DB-native ids. On an
// EXISTING database (production's migrated table) it acts as a REPAIR: a row
// that has metadata but NULL data bytes is backfilled from the committed file
// so /api/media/<id> can serve it, while rows that already have bytes — or
// metadata that is valid — are left untouched (id, created_at, updated_at and
// file_name/content_type/file_size are preserved). Idempotent + safe on every
// cold start; only runs when the committed asset file is readable at runtime.
export async function seedMigratedMedia(client: PoolClient): Promise<void> {
  const seedSlots = [
    {
      slot_key: "global_collaboration_video",
      file_name: "API-Center.mp4",
      content_type: "video/mp4",
      relative: join("public", "videos", "API-Center.mp4"),
    },
    {
      slot_key: "global_collaboration_image",
      file_name: "photo-1552664730-d307ca884978.jpg",
      content_type: "image/jpeg",
      relative: join("public", "images", "photo-1552664730-d307ca884978.jpg"),
    },
  ];

  for (const slot of seedSlots) {
    const filePath = join(process.cwd(), slot.relative);
    if (!existsSync(filePath)) continue;
    const data = readFileSync(filePath);
    await client.query(
      `INSERT INTO media_assets (slot_key, file_name, content_type, file_size, data, created_at, updated_at)
       VALUES ($1, $2, $3, $4, $5, now(), now())
       ON CONFLICT (slot_key) DO UPDATE SET
         data = COALESCE(media_assets.data, EXCLUDED.data),
         file_name = COALESCE(media_assets.file_name, EXCLUDED.file_name),
         content_type = COALESCE(media_assets.content_type, EXCLUDED.content_type),
         file_size = COALESCE(media_assets.file_size, EXCLUDED.file_size)
       WHERE media_assets.data IS NULL`,
      [slot.slot_key, slot.file_name, slot.content_type, data.length, data]
    );
  }
}