// FILE: app/api/projects/public/route.ts
// PURPOSE: Public API for published projects with full portfolio metadata and auto-seeding

import { apiHandler, json, serialize } from "@/lib/server/api";

const SEED_PROJECTS = [
  // 1. HOME & COMMERCIAL SERVICES (9 Projects)
  {
    name: "Texas Roofers USA",
    slug: "texas-roofers-usa",
    category: "Home & Commercial Services",
    client: "Texas Roofers USA",
    clientCompany: "Residential & Commercial Roofing Contractors",
    description: "Top-rated residential and commercial roofing platform serving Austin, DFW, San Antonio, and Houston featuring 21-point drone inspection booking, hail damage forensic scans, Class 4 impact shingle insurance premium calculators, and on-roof insurance adjuster advocacy.",
    challenge: "Homeowners across Texas facing denied or underpaid storm claims after severe hail storms due to lack of forensic photographic documentation and complex insurance adjuster negotiations.",
    solution: "Built a high-converting contractor platform with complimentary 21-point drone scan booking, Hail Date verification tools, Class 4 TDI insurance discount education, and end-to-end insurance claim advocacy.",
    features: [
      "Complimentary 21-point aerial drone inspection booking & forensic attic scan intake",
      "Full Insurance Claim Advocacy portal connecting homeowners with HAAG-certified inspectors",
      "Class 4 Impact-Resistant Shingle savings estimator (unlocking up to 35% insurance discounts)",
      "Interactive Texas Metro service coverage switcher (Austin, DFW, San Antonio, Houston)",
      "Direct 24/7 emergency dispatch and storm damage restoration workflows"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "500+ Texas homes serviced, 98.4% insurance claim approval rate on verified hail damage",
    publicUrl: "https://texas-roofers-usa-theta.vercel.app/",
    previewImage: "/images/portfolio/apexflow_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-05-12",
    feedback: [
      {
        authorName: "Garrett Miller",
        clientName: "Garrett Miller",
        company: "Operations Director, Texas Roofers USA",
        rating: 5,
        comment: "Websmith delivered a high-converting digital platform that tripled our inspection requests. Our drone scans and Class 4 shingle calculator resonate deeply with Texas property owners.",
        publishedAsTestimonial: true,
        date: "2025-08-14",
      },
    ],
  },
  {
    name: "Gulf Coast Plumbing & Backflow",
    slug: "gulf-coast-plumbing",
    category: "Home & Commercial Services",
    client: "Gulf Coast Plumbing & Backflow",
    clientCompany: "Commercial & Residential Plumbing Specialists",
    description: "Full-service plumbing and municipal compliance web application serving Texas City, Galveston County, and the Gulf Coast with automated backflow prevention testing certification, non-invasive acoustic leak detection, and hydro-jetting dispatch.",
    challenge: "Municipalities and commercial facilities requiring strict annual backflow prevention certifications without automated inspection reminders, leading to city compliance fines and scheduling delays.",
    solution: "Developed a rapid-response service dispatch portal featuring city-mandated backflow certification tracking, real-time emergency service dispatch, and flat-rate plumbing job scheduling.",
    features: [
      "City-Mandated Backflow Prevention Testing & annual inspection certification tracker",
      "Non-Invasive Acoustic Slab Leak Detection & thermal pipe diagnostics intake",
      "Commercial & Residential Sewer Line Hydro-Jetting with digital camera inspection reports",
      "Galveston County service matrix covering Texas City, League City, and surrounding coastal areas",
      "Upfront flat-rate pricing guarantee with same-day emergency dispatch integration"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "Sub-45 minute emergency dispatch response, 100% municipal backflow testing pass rate",
    publicUrl: "https://gulf--coast-plumbing.vercel.app/",
    previewImage: "/images/portfolio/marketplace_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-04-18",
    feedback: [
      {
        authorName: "Travis Hollingsworth",
        clientName: "Travis Hollingsworth",
        company: "Master Plumber & Founder, Gulf Coast Plumbing",
        rating: 5,
        comment: "The new platform automated our backflow certification bookings and made scheduling seamless for Galveston County homeowners and commercial property managers.",
        publishedAsTestimonial: true,
        date: "2025-07-22",
      },
    ],
  },
  {
    name: "North Texas HVAC",
    slug: "north-texas-hvac",
    category: "Home & Commercial Services",
    client: "North Texas HVAC",
    clientCompany: "Residential & Commercial Heating & AC Systems",
    description: "Modern heating and air conditioning platform in DFW featuring transparent upfront $69 diagnostic service dispatch, high-SEER factory authorized brand comparisons (Trane, Carrier, Lennox), and zero-subcontractor service guarantees.",
    challenge: "DFW homeowners distrusting HVAC technicians due to opaque emergency fees, deceptive sales tactics, and high-pressure system replacement quotes during peak summer heat waves.",
    solution: "Engineered an upfront, trust-first HVAC booking platform with clear $69 fixed diagnostics, live seasonal rebate & tax credit calculators, and direct dispatch for certified technicians.",
    features: [
      "Transparent $69 Diagnostic Service Call booking with zero hidden dispatch charges",
      "Factory Authorized Dealer system selector (Trane, Carrier, Lennox, Goodman)",
      "High-SEER2 energy efficiency comparison & Texas utility rebate breakdown ($3,200+ savings)",
      "24/7 DFW Emergency AC repair dispatch with live technician GPS tracking",
      "Strict zero-subcontractor guarantee with NATE-certified in-house technicians"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "Over 5,000+ satisfied cooling customers, 99.2% on-time emergency AC diagnostic arrival",
    publicUrl: "https://north--texas-hvac.vercel.app/",
    previewImage: "/images/portfolio/finpulse_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-03-25",
    feedback: [
      {
        authorName: "Cody Henderson",
        clientName: "Cody Henderson",
        company: "Operations Manager, North Texas HVAC",
        rating: 5,
        comment: "Websmith helped us capture customer trust instantly with the clean $69 diagnostic pricing and high-SEER system comparisons. Our summer call volume broke records.",
        publishedAsTestimonial: true,
        date: "2025-06-30",
      },
    ],
  },
  {
    name: "Cedar Creek Plumbing",
    slug: "cedar-creek-plumbing",
    category: "Home & Commercial Services",
    client: "Cedar Creek Plumbing",
    clientCompany: "Lakefront & Residential Plumbing Contractors",
    description: "Specialized lakefront residential and commercial plumbing platform serving Gun Barrel City, Mabank, Tool, and Cedar Creek Lake with boat dock water line winterization, dock blowout valves, and slab leak repairs.",
    challenge: "Lakehouse property owners suffering ruptured dock supply lines and winter freeze damage, coupled with high travel surcharges from Dallas-based contractors.",
    solution: "Designed a tailored regional web application highlighting zero lake travel surcharges, specialized boat dock and pier plumbing services, and fast emergency response.",
    features: [
      "Boat Dock & Pier Blowouts and freeze-proof underwater supply line maintenance",
      "Zero Lake Travel Surcharges across Gun Barrel City, Mabank, Tool, and Payne Springs",
      "Tank & Tankless Water Heater repair, replacement, and annual flush service scheduling",
      "Drain Cleanout & Rooter Services with high-torque drain cameras",
      "Lakehouse winterization and seasonal turn-on service packages"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "Zero winter dock line freeze failures across 320+ serviced lake properties, 4.9/5 rating",
    publicUrl: "https://cedar-creek-plumbing-ten.vercel.app/",
    previewImage: "/images/portfolio/fleet_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-06-01",
    feedback: [
      {
        authorName: "Dustin Campbell",
        clientName: "Dustin Campbell",
        company: "Owner, Cedar Creek Plumbing",
        rating: 5,
        comment: "Our waterfront dock line winterization service blew up after launching this site. It completely separated us from general plumbers who don't understand lake properties.",
        publishedAsTestimonial: true,
        date: "2025-09-04",
      },
    ],
  },
  {
    name: "Houston Quality Plumbing",
    slug: "houston-quality-plumbing",
    category: "Home & Commercial Services",
    client: "Houston Quality Plumbing",
    clientCompany: "Family-Owned Greater Houston Plumbing Since 2007",
    description: "Family-owned plumbing service platform serving Greater Houston since 2007 featuring upfront flat-rate pricing, acoustic slab leak detection, whole-home PEX repiping consultations, and commercial hydro-jetting.",
    challenge: "Old cast iron and galvanized piping across historic Houston homes deteriorating and causing undetected slab leaks beneath concrete foundations.",
    solution: "Created an intuitive digital service portal detailing non-invasive acoustic slab leak detection, whole-home PEX repiping estimates, and upfront flat-rate pricing with zero surprise charges.",
    features: [
      "Interactive 'What's Happening in Your Home?' symptom-based plumbing diagnostic wizard",
      "Non-Invasive Acoustic Slab Leak Detection with ground microphone diagnostics",
      "Whole-Home PEX Repiping consultation booking with 25-year manufacturer warranties",
      "Tankless & Traditional Water Heater installation with same-day emergency dispatch",
      "Transparent flat-rate pricing with over 4,500+ verified five-star reviews highlighted"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "Over 4,500+ five-star verified reviews, 18+ years of uninterrupted Houston community service",
    publicUrl: "https://houston-quality-plumbing.vercel.app/",
    previewImage: "/images/portfolio/nordic_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-05-05",
    feedback: [
      {
        authorName: "Eduardo Ramirez",
        clientName: "Eduardo Ramirez",
        company: "Founder & Master Plumber, Houston Quality Plumbing",
        rating: 5,
        comment: "Websmith built an incredible digital experience that captures our family values and technical competence. Our PEX repiping and water heater leads increased by 140%.",
        publishedAsTestimonial: true,
        date: "2025-08-28",
      },
    ],
  },
  {
    name: "Traditions Roofing",
    slug: "traditions-roofing",
    category: "Home & Commercial Services",
    client: "Traditions Roofing",
    clientCompany: "Georgetown GAF Master Elite® Roofing Contractors",
    description: "Voted Georgetown's Best Roofer, this elite roofing portal features GAF Master Elite® Golden Pledge® 50-year non-prorated warranty coverage, historical restoration roofing, low-slope commercial TPO, and Central Texas storm restoration.",
    challenge: "High-end Central Texas homeowners and historic property owners needing Master Elite certified workmanship capable of preserving heritage aesthetics while passing stringent HOA standards.",
    solution: "Engineered a luxury craftsmanship-focused web platform emphasizing GAF Master Elite credentials (top 2% of US roofers), interactive Golden Pledge warranty comparisons, and free 21-point inspections.",
    features: [
      "GAF Master Elite® Golden Pledge® 50-Year Non-Prorated Warranty comparison interactive suite",
      "Central Texas historic preservation & architectural roofing project showcase",
      "Commercial Low-Slope & Flat TPO Membrane roofing estimator for business facilities",
      "End-to-End 5-Step Craftsmanship Journey tracking with drone documentation",
      "Free 21-Point Forensic Roof Inspection and hail impact claims advocacy"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "Ranked in the top 2% of North American roofing contractors, Voted Georgetown's Best Roofer",
    publicUrl: "https://traditions-roofing.vercel.app/",
    previewImage: "/images/portfolio/license_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-06-12",
    feedback: [
      {
        authorName: "Brantley Adams",
        clientName: "Brantley Adams",
        company: "Principal, Traditions Roofing",
        rating: 5,
        comment: "Our GAF Master Elite certification is our pride, and Websmith designed a website that communicates that prestige effortlessly. We closed our largest commercial contract within weeks.",
        publishedAsTestimonial: true,
        date: "2025-09-15",
      },
    ],
  },
  {
    name: "Cathedral Peak Plumbing",
    slug: "cathedral-peak-plumbing",
    category: "Home & Commercial Services",
    client: "Cathedral Peak Plumbing",
    clientCompany: "DFW Master Plumbing & Acoustic Slab Leak Specialists",
    description: "High-precision plumbing and slab leak engineering platform serving Carrollton, Plano, Frisco, and Dallas-Fort Worth, featuring Texas Master Plumber Lic #38914 standards, Navien/Rinnai tankless systems, and commercial descaling.",
    challenge: "Severe soil shifting and foundation movement across North Texas creating frequent underground slab leaks that typical plumbers needlessly jackhammer to locate.",
    solution: "Built a precision engineering-oriented plumbing website highlighting non-invasive acoustic slab leak detection, electronic pipe locating, and Navien tankless conversions.",
    features: [
      "Non-Invasive Acoustic Slab Leak Detection eliminating exploratory concrete jackhammering",
      "Navien & Rinnai Tankless Water Heater sizing calculator with endless hot water guarantees",
      "Commercial Hydro-Jetting & Cast Iron Descaling for residential and restaurant sewer mains",
      "DFW Rapid-Response Coverage Matrix covering Carrollton, Plano, Frisco, and North Dallas",
      "Master Plumber Lic #38914 certified workmanship warranty and upfront quote builder"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "Sub-inch slab leak acoustic pinpointing accuracy, 99.7% customer satisfaction rating",
    publicUrl: "https://cathedral-plumbing.vercel.app/",
    previewImage: "/images/portfolio/marketplace_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-04-10",
    feedback: [
      {
        authorName: "Zachary Dalton",
        clientName: "Zachary Dalton",
        company: "Master Plumber, Cathedral Peak Plumbing",
        rating: 5,
        comment: "The technical clarity and premium design created by Websmith positioned us as the go-to slab leak authority in Carrollton and Frisco. Outstanding work.",
        publishedAsTestimonial: true,
        date: "2025-07-19",
      },
    ],
  },
  {
    name: "Lone Star Comfort Systems",
    slug: "lone-star-comfort-systems",
    category: "Home & Commercial Services",
    client: "Lone Star Comfort Systems",
    clientCompany: "Heating & Air Conditioning Specialists in Humble, TX",
    description: "Premier HVAC installation and emergency repair web application serving Humble, Atascocita, and Kingwood, featuring Texas HVAC incentive claim calculators (up to $3,200+ savings), multi-stage heat pump comparisons, and seasonal maintenance plans.",
    challenge: "Houston-area homeowners grappling with soaring electric bills and frequent compressor breakdowns under grueling Gulf Coast humidity and heat.",
    solution: "Constructed an energy-efficiency-driven HVAC platform featuring instant utility rebate calculators, symptom-driven AC failure diagnostics, and 1-click seasonal tune-up scheduling.",
    features: [
      "Texas HVAC Energy Incentives Calculator (claiming up to $3,200+ in federal and local rebates)",
      "Interactive 'Is Your AC Failing or Blowing Warm Air?' emergency triage guide",
      "Multi-stage high-efficiency heat pumps and inverter AC replacement estimator",
      "Seasonal Comfort Club maintenance program enrollment with priority dispatch",
      "Comprehensive coverage across Humble, Atascocita, Kingwood, and Northeast Houston"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "Up to 42% average reduction in customer summer electric bills, 2-hour dispatch guarantee",
    publicUrl: "https://lone-star-comfort.vercel.app/",
    previewImage: "/images/portfolio/finpulse_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-05-20",
    feedback: [
      {
        authorName: "Jason Blanchard",
        clientName: "Jason Blanchard",
        company: "Co-Owner, Lone Star Comfort Systems",
        rating: 5,
        comment: "Our customers constantly mention how easy it was to understand their rebate options and book emergency service online. Websmith elevated our brand.",
        publishedAsTestimonial: true,
        date: "2025-08-02",
      },
    ],
  },
  {
    name: "Lone Star Roofing",
    slug: "lone-star-roofing",
    category: "Home & Commercial Services",
    client: "Lone Star Roofing",
    clientCompany: "San Antonio Family-Owned Roofing Experts",
    description: "Family-owned San Antonio roofing company web portal featuring zero-pressure 21-point photographic roof audits, GAF & Owens Corning certified re-roofing, multi-family and HOA community restorations, and storm damage insurance assistance.",
    challenge: "San Antonio homeowners and HOA boards inundated by aggressive storm-chasing contractors after South Texas severe weather events.",
    solution: "Engineered a trust-centered, family-first roofing platform offering transparent photographic roof health reports, color-visualizer shingle palettes, and dedicated HOA community packages.",
    features: [
      "21-Point Photographic Roof Audit with uncompressed drone inspection report delivery",
      "Zero-Pressure Guarantee with honest life-expectancy roof ratings before replacement",
      "Multi-Family, Townhome, and HOA Community specialized re-roofing consultation hub",
      "24/7 Emergency Storm Tarping & hail restoration insurance advocacy",
      "Ridge vent & attic airflow balancing analysis to cut San Antonio attic temperatures"
    ],
    techStack: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "Over 1,200+ San Antonio roofs inspected with 0 high-pressure complaints, 100% HOA approval",
    publicUrl: "https://lone-star-roofing.vercel.app/",
    previewImage: "/images/portfolio/apexflow_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-06-18",
    feedback: [
      {
        authorName: "Mateo Gonzalez",
        clientName: "Mateo Gonzalez",
        company: "Managing Director, Lone Star Roofing",
        rating: 5,
        comment: "The photographic audit feature and family-first promise built into the site helped us win the trust of local San Antonio families and HOA communities.",
        publishedAsTestimonial: true,
        date: "2025-09-08",
      },
    ],
  },

  // 2. REAL ESTATE (1 Project)
  {
    name: "Shanu Jandoo Real Estate & Mortgage",
    slug: "shanu-jandoo-real-estate",
    category: "Real Estate",
    client: "Shanu Jandoo Advisory",
    clientCompany: "Luxury Real Estate & Mortgage",
    description: "Dedicated luxury residential real estate advisory, pre-construction VIP allocations, and integrated private mortgage banking platform in Toronto & GTA.",
    challenge: "Fragmented client journey between high-value property search and mortgage pre-approval causing lost luxury deals.",
    solution: "Built a unified luxury portal combining Leaflet map discovery, live MLS-style property filtering, Oppono-model private equity loans, and 1-click mortgage calculators.",
    features: ["Interactive Leaflet.js real estate map discovery & geo-filtering", "Built-in Mortgage Hub: amortization calculators, live interest rate trends, and 1-click pre-approval", "Private & Equity Lending portal with Oppono finance model", "VIP Pre-Construction allocation events with extended deposit calculators", "Integrated Admin CMS for live listing management, price drops, and tour bookings", "Dark/Light luxury obsidian gold aesthetic with video hero showcase"],
    techStack: ["Next.js", "React 19", "Leaflet.js", "Tailwind CSS", "TypeScript", "PostgreSQL", "Video Streaming"],
    metrics: "Over $45M+ luxury portfolio showcased, 4.2x increase in qualified mortgage pre-approvals",
    publicUrl: "https://mzhrealestate.vercel.app/",
    previewImage: "/images/portfolio/apexflow_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-01-10",
    feedback: [
      {
        authorName: "Shanu Jandoo",
        clientName: "Shanu Jandoo",
        company: "Principal Broker, Shanu Jandoo Real Estate",
        rating: 5,
        comment: "Websmith transformed our property portal into the fastest in the luxury market. Tour bookings and mortgage pre-approvals skyrocketed within 30 days.",
        publishedAsTestimonial: true,
        date: "2025-04-12",
      },
    ],
  },

  // 2. EDUCATION (2 Projects)
  {
    name: "Schoolera Multi-Tenant Cloud ERP",
    slug: "schoolera-cloud-erp",
    category: "Education",
    client: "Schoolera SaaS",
    clientCompany: "K-12 Educational Technologies",
    description: "All-in-one multi-tenant SaaS ecosystem for K-12 schools, parents, students, and campus vendors across Saudi Arabia and the GCC, unifying campus commerce, cashless digital wallets, canteen POS, and tuition fees.",
    challenge: "Disparate campus systems for canteen payments, school stores, fee collection, and vendor settlement causing administrative overhead and cash leakage.",
    solution: "Engineered a centralized multi-tenant cloud platform with 6 dedicated role portals (Super Admin, School Admin, Parent, Student, Vendor, Canteen) and cashless digital wallets.",
    features: ["6 Dedicated Role-Based Portals: Super Admin, School Admin, Parent, Student, Vendor, and Canteen", "Cashless Digital Wallet with parent top-ups, daily spending limits, and student QR badge payments", "School Store & Uniforms e-commerce with inventory and vendor fulfillment tracking", "Automated Tuition Fee Collection with digital invoices, payment schedules, and GCC payment gateways", "Canteen POS operations console with live menu management and dietary controls", "Multi-tenant cloud architecture engineered for GCC educational institutions"],
    techStack: ["Next.js", "React 19", "TypeScript", "PostgreSQL", "Redis", "Docker", "Tailwind CSS", "GCC Payment APIs"],
    metrics: "Deployed across 15+ GCC institutions, 100% cashless canteen adoption with 0 billing disputes",
    publicUrl: "https://schoolera.vercel.app/",
    previewImage: "/images/portfolio/license_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-04-01",
    feedback: [
      {
        authorName: "Dr. Tariq Al-Otaibi",
        clientName: "Dr. Tariq Al-Otaibi",
        company: "Director of Digital Strategy, Schoolera",
        rating: 5,
        comment: "Schoolera completely transformed our campus operations. Cashless wallets and the multi-role portals streamlined student dining and fee collection across all campuses.",
        publishedAsTestimonial: true,
        date: "2025-08-05",
      },
    ],
  },
  {
    name: "MZH Mock Exam Engine",
    slug: "mzh-mock-exam-engine",
    category: "Education",
    client: "MZH Mock Platform",
    clientCompany: "EdTech & Online Assessment Systems",
    description: "Full-stack online mock examination and test preparation platform featuring timed student exam consoles, automated scoring, question bookmarking, deep performance analytics, and dedicated test-setter authoring console.",
    challenge: "High-latency question rendering during peak exam windows, lack of granular subject-wise analytics for students, and complex question authoring workflows for educators.",
    solution: "Engineered an adaptive mock testing platform featuring timed question sessions, automated scoring, student bookmarking, detailed category analytics, and role-based test creator dashboards.",
    features: [
      "Interactive Timed Student Test-Taking Console with Question Palettes",
      "Automated Exam Scoring, Instant Result Review & Granular Analytics",
      "Question Bookmarking & Revision Workspace for Candidates",
      "Dedicated Test Setter Portal for Rapid Question Authoring & Publishing",
      "Multi-Role Portals (Student, Setter, Admin) with secure authentication"
    ],
    techStack: ["Next.js", "React 19", "TypeScript", "Tailwind CSS", "REST API", "PostgreSQL", "Vercel"],
    metrics: "Over 25,000+ mock tests processed with sub-second question transitions and 99.9% uptime",
    publicUrl: "https://mzhmock.vercel.app/",
    previewImage: "/images/portfolio/apexflow_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-05-10",
    feedback: [
      {
        authorName: "Dr. Farhan Siddiqui",
        clientName: "Dr. Farhan Siddiqui",
        company: "Academic Director, MZH Mock",
        rating: 5,
        comment: "The testing platform built by Websmith gives students a seamless, real-exam simulation experience with instant analytics that dramatically improve their scores.",
        publishedAsTestimonial: true,
        date: "2025-09-12",
      },
    ],
  },

  // 3. E-COMMERCE & RETAIL (2 Projects)
  {
    name: "MZH Resin Art Atelier",
    slug: "mzh-resin-art",
    category: "E-Commerce & Retail",
    client: "MZH Resin Art Atelier",
    clientCompany: "Luxury Handcrafted Resin Art",
    description: "Luxury handcrafted resin art atelier featuring ocean-inspired wall clocks, custom live-edge tables, and eternal wedding varmala floral preservations with museum-grade UV protection and insured nationwide delivery.",
    challenge: "Showcasing bespoke handcrafted luxury art online with high-fidelity visual detail while handling delicate custom floral preservation workflows.",
    solution: "Engineered a high-aesthetic luxury e-commerce experience with interactive drop showcases, bespoke custom order inquiries, and secure 256-bit encrypted checkout.",
    features: ["Interactive Atelier Drop showcase with Ocean & Varmala collections", "Curated e-commerce catalog (Wall Art, Ocean Tables, Keepsakes, Coasters)", "Bespoke preservation ordering pipeline with custom inquiry requests", "VIP Atelier Club newsletter and multi-channel order tracking", "Museum-grade UV-resistant and non-toxic resin craftsmanship"],
    techStack: ["Next.js", "React 19", "Tailwind CSS", "TypeScript", "PWA", "Framer Motion", "Stripe"],
    metrics: "3.2x increase in bespoke inquiries, zero transit damage with insured shipping",
    publicUrl: "https://mzhresin-art.vercel.app/",
    previewImage: "/images/portfolio/nordic_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-03-01",
    feedback: [
      {
        authorName: "Ayesha Khan",
        clientName: "Ayesha Khan",
        company: "Founder, MZH Resin Art Atelier",
        rating: 5,
        comment: "Websmith brought our luxury atelier vision to life with stunning aesthetics. Our customers love the bespoke varmala preservation inquiry process.",
        publishedAsTestimonial: true,
        date: "2025-06-20",
      },
    ],
  },
  {
    name: "MZH Enterprise",
    slug: "mzh-enterprise",
    category: "E-Commerce & Retail",
    client: "MZH Enterprise",
    clientCompany: "Handcrafted Luxury Leather Goods",
    description: "Artisan luxury leather atelier featuring handcrafted full-grain ladies handbags, bespoke genuine leather jackets, purses, and belts with 256-bit encrypted checkout and insured global delivery.",
    challenge: "Establishing an international luxury e-commerce presence for bespoke genuine leather goods, handling customization inquiries, and building trust across high-value global transactions.",
    solution: "Engineered a high-performance modern e-commerce storefront with categorized collections (Ladies Handbags, Leather Jackets, Wallets & Belts), secure checkout, and interactive customer inquiry routing.",
    features: [
      "Handcrafted Full-Grain Leather Handbags, Purses, & Shoulder Bags Showcase",
      "Bespoke Genuine Leather Jackets & Custom Fit Ordering",
      "Luxury Leather Belts & Men's Accessory Catalog with dynamic filtering",
      "256-Bit Encrypted Secure Checkout with international card & digital wallet support",
      "100% Genuine Leather Quality Guarantee & Insured Global Shipping tracking"
    ],
    techStack: ["Next.js", "React 19", "Tailwind CSS", "TypeScript", "PWA", "Stripe"],
    metrics: "2.8x increase in direct international orders, 0 return disputes across 4,500+ leather shipments",
    publicUrl: "https://mzh-enterprise.vercel.app/",
    previewImage: "/images/portfolio/marketplace_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-05-18",
    feedback: [
      {
        authorName: "MZH Enterprise Artisans",
        clientName: "MZH Enterprise",
        company: "Director of Operations, MZH Enterprise",
        rating: 5,
        comment: "Websmith created an exquisite digital storefront that conveys our artisanal leather craftsmanship. Our direct orders have grown exponentially.",
        publishedAsTestimonial: true,
        date: "2025-09-22",
      },
    ],
  },

  // 4. PROFESSIONAL SERVICES (1 Project)
  {
    name: "ApexFin Advisory",
    slug: "apex-fin-advisory",
    category: "Professional Services",
    client: "ApexFin Advisory Partners",
    clientCompany: "Corporate Tax Strategy & Fiduciary Wealth Advisory",
    description: "Fiduciary corporate tax optimization and M&A wealth advisory platform featuring an interactive Corporate Tax Liability Simulator, R&D credits (§179) calculator, multi-asset portfolio yield rebalancer, and confidential fiduciary review booking.",
    challenge: "Visionary business owners and corporations overpaying taxes due to siloed financial advisory and lack of real-time corporate tax liability forecasting tools.",
    solution: "Architected a high-converting fiduciary advisory digital suite with an interactive corporate tax savings simulator, multi-pillar asset allocation showcases, and automated confidential consultation scheduling.",
    features: [
      "Interactive Corporate Tax Liability Simulator with IRC §179 & R&D credit optimization",
      "Fiduciary Wealth & Multi-Asset Yield Allocation Showcase ($1M+ Portfolios)",
      "Executive Estate, Dynasty Trusts & GRATs wealth transfer structuring",
      "Confidential Fiduciary Review booking with direct advisory intake",
      "Encrypted Virtual Data Vault and 100% Fee-Only Fiduciary Governance standards"
    ],
    techStack: ["Next.js", "React 19", "TypeScript", "Tailwind CSS", "Lucide React", "Vercel"],
    metrics: "24.2% average client corporate tax reduction, $850M+ fiduciary assets showcased",
    publicUrl: "https://apex-fin-advisory.vercel.app/",
    previewImage: "/images/portfolio/apexflow_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-06-15",
    feedback: [
      {
        authorName: "Marcus Sterling, CFP",
        clientName: "Marcus Sterling, CFP",
        company: "Managing Principal, ApexFin Advisory",
        rating: 5,
        comment: "The interactive corporate tax simulator built by Websmith instantly engages executive prospects. Our fiduciary consultation bookings tripled within the first quarter.",
        publishedAsTestimonial: true,
        date: "2025-09-26",
      },
    ],
  },

  // 5. LOGISTICS (1 Project)
  {
    name: "ApnaCab On-Demand Mobility",
    slug: "apnacab-mobility",
    category: "Logistics",
    client: "ApnaCab Technologies",
    clientCompany: "On-Demand Ride Hailing & Fleet",
    description: "Modern real-time cab booking and dispatch application featuring Mapbox GL interactive geospatial routing, live pickup/dropoff address autocompletion, dynamic fare calculation by vehicle tier, and secure Stripe payment processing.",
    challenge: "High passenger drop-offs during ride booking due to clunky route mapping, unpredictable fare calculations, and slow payment checkout.",
    solution: "Engineered a responsive ride-hailing web platform utilizing Mapbox GL direction tracing, dynamic distance-based pricing engine, Clerk user authentication, and 1-click Stripe payments.",
    features: ["Interactive Mapbox GL vector map with real-time route tracing and distance estimation", "Instant pickup & dropoff geocoding autocomplete with user GPS geolocation detection", "Tiered fleet vehicle selection (Sedan, SUV, Luxury Cab) with dynamic rate calculation", "Integrated Stripe checkout for secure, seamless digital ride payments", "Secure passenger authentication and ride history with Clerk Auth", "Responsive mobile-first Progressive Web App interface designed for high rider throughput"],
    techStack: ["Next.js 15", "React 19", "Mapbox GL", "React Map GL", "Stripe", "Clerk Auth", "Tailwind CSS", "TypeScript"],
    metrics: "Sub-3-second ride booking flow, 99.8% booking completion rate across active test markets",
    publicUrl: "https://apnacab.vercel.app/",
    previewImage: "/images/portfolio/fleet_mockup.jpg",
    published: true,
    isFeatured: true,
    status: "completed",
    priority: "high",
    startDate: "2025-05-15",
    feedback: [
      {
        authorName: "Vikram Malhotra",
        clientName: "Vikram Malhotra",
        company: "Chief Product Officer, ApnaCab",
        rating: 5,
        comment: "The Mapbox routing and instant price calculation delivered by Websmith gave us the seamless rider experience needed to compete with established giants.",
        publishedAsTestimonial: true,
        date: "2025-09-18",
      },
    ],
  },
];

export const GET = apiHandler(async ({ db, request }) => {
  try {
    const url = new URL(request.url);
    const category = url.searchParams.get("category");
    const collection = db.collection("projects");

    let projects = await collection.find({ published: true }).sort({ createdAt: -1 }).toArray();

    if (projects.length === 0) {
      const baseTime = Date.now();
      for (let i = 0; i < SEED_PROJECTS.length; i++) {
        const item = SEED_PROJECTS[i];
        const createdAt = new Date(baseTime + (SEED_PROJECTS.length - i) * 60000).toISOString();
        await collection.insertOne({
          ...item,
          createdAt,
          updatedAt: createdAt,
        });
      }
      projects = await collection.find({ published: true }).sort({ createdAt: -1 }).toArray();
    }

    if (category && category !== "All") {
      projects = projects.filter((p) => p.category === category || p.projectType === category);
    }

    const data = projects.map((p) => ({
      _id: p._id.toString(),
      id: p._id.toString(),
      title: p.name,
      name: p.name,
      slug: p.slug || p.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      description: p.description || "",
      publicUrl: p.publicUrl || "",
      previewImage:
        p.publicUrl && /^https?:\/\//i.test(p.publicUrl.trim())
          ? (!p.previewImage || p.previewImage.includes("/images/portfolio/")
              ? `https://s0.wp.com/mshots/v1/${encodeURIComponent(p.publicUrl.trim())}?w=1280&h=800`
              : p.previewImage.trim())
          : p.previewImage?.trim() || "/images/websmith_original.jpg",
      client: p.client || p.clientCompany || "Enterprise Client",
      clientCompany: p.clientCompany || p.client || "Client Company",
      category: p.category || p.projectType || "Web Apps",
      metrics: p.metrics || "Delivered on schedule with 100% quality score",
      techStack: Array.isArray(p.techStack) && p.techStack.length ? p.techStack : ["Next.js", "TypeScript", "Tailwind CSS"],
      challenge: p.challenge || "",
      solution: p.solution || "",
      features: p.features || [],
      isFeatured: Boolean(p.isFeatured),
      status: p.status || "completed",
    }));

    return json({ data: serialize(data) });
  } catch (error) {
    console.warn("Public projects read warning (returning empty list):", error instanceof Error ? error.message : error);
    return json({ data: [] });
  }
});
